package Grapher.ApiDataRetriever;

import Grapher.ApiDataRetriever.JSONHandler.DataStructure;
import Grapher.ApiDataRetriever.JSONHandler.JsonBodyHandler;
import Grapher.ApiDataRetriever.Exceptions.ClientApiUrlException;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.concurrent.ExecutionException;

/** An API Connection class used to Handle Connections to the API and make requests.
 *
 * @author Henry Wessels
 * @version 1.0
 * @since 2022-03-16
 */
public class APIConnection {
    /** This is the Http Client created for the connection to the remote API
     *
     * This is created in the constructor for this class.
     */
    private final HttpClient ClientAPI;
    /** The URL of the remote API
     *
     * This is the URL the request will be sent to after it is built.
     * It is important that this is given as a fully qualified web address contained in a String.
     */
    private final String ClientURL;
    /** The Http Request that is sent to the API.
     *
     * This is generated by the class method 'BuildRequest'
     */
    private HttpRequest APIRequest;

    //region ====[ Constructions ]====
    /** The Constructor for APIConnection that sets up the HttpClient and Client's URL.
     *
     * @param clientAPIUrl The URL of the targeted APi as a String.
     */
    public APIConnection(String clientAPIUrl) {
        this.ClientAPI = HttpClient.newHttpClient();
        this.ClientURL = clientAPIUrl;
    }
    //endregion

    //region ====[ Send Request ]====
    /** This is used to send a request to the API web services,
     * and get the data needed as an object of the DataStructure class.
     *
     * @return DataStructure object that has the request body data mapped to it.
     */
    public DataStructure SendRequest() {
        try {
            if (this.ClientURL == null) throw new ClientApiUrlException("NullValue", "No up stream API URL");
            return this.SendRequest(this.ClientURL, "60");
        } catch (ClientApiUrlException c) {
            System.out.println(c.getMessage());
        }
        return null;
    }

    /** This is used to send a request to the API web services,
     * and get the data needed as an object of the DataStructure class.
     *
     * @param UpStreamURL The API URL to request data from as a String.
     * @return DataStructure object that has the request body data mapped to it.
     */
    public DataStructure SendRequest(String UpStreamURL) {
        return this.SendRequest(UpStreamURL, "60");
    }

    /** This is used to send a request to the API web services,
     * and get the data needed as an object of the DataStructure class.
     *
     * @param UpStreamURL The API URL to request data from as a String.
     * @param timeoutInMinutes The amount of time taken to fail a request in minutes as a String.
     * @return DataStructure object that has the request body data mapped to it.
     */
    public DataStructure SendRequest(String UpStreamURL, String timeoutInMinutes) {
        BuildRequest(UpStreamURL);

        try {
            return ClientAPI.sendAsync(
                    APIRequest, new JsonBodyHandler<>(DataStructure.class)
            ).get(
                    Long.parseLong(timeoutInMinutes), TimeUnit.MINUTES
            ).body().get();
        } catch (InterruptedException i) {
            System.out.println(i.getMessage());
        } catch (ExecutionException e) {
            System.out.println(e.getMessage());
        } catch (TimeoutException t) {
            System.out.println(t.getMessage());
        }
        return null;
    }
    //endregion

    //region ====[ Private Functions ]====
    /** The BuildRequest method builds out a HttpRequest using the ApiURL,
     * it has a static header of [ accept - application/json ].
     *
     * @param ApiURL The URL of the API web service as a String.
     * @see HttpRequest
     */
    private void BuildRequest(String ApiURL) {
        APIRequest = HttpRequest.newBuilder(
                URI.create(ApiURL)
        ).header(
                "accept", "application/json"
        ).build();
    }
    //endregion
}
