name: Main Workflow

on:
  push:
    branches: [ main ]
    tags:
      - v**
  workflow_dispatch:

jobs:
  Test:
    uses: GingerNinja2962/FoondaMate_Graph_Project/.github/workflows/Tests.yml@main

  Build:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: Test
    uses: GingerNinja2962/FoondaMate_Graph_Project/.github/workflows/Build.yml@main

  Release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: Build
    uses: GingerNinja2962/FoondaMate_Graph_Project/.github/workflows/Release.yml@main

  Cleanup:
    needs: Release
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch [Cleanup]
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WEBHOOK_SECRET }}
          event-type: Cleanup-Artifacts
          client-payload: '{"event_type": "delete_all_artifacts", "client_payload": {"parent_runid": "${{github.run_id}}", "parent_repo": "${{ github.repository }}"}}'
