name: Main Workflow

on:
  push:
    branches: [ main ]
    tags:
      - v**
  workflow_dispatch:


jobs:
  Test:
    uses: GingerNinja2962/FoondaMate_Graph_Project/.github/workflows/Tests.yml@main


  Build:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: Test
    uses: GingerNinja2962/FoondaMate_Graph_Project/.github/workflows/Build.yml@main


  Release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: Build
    uses: GingerNinja2962/FoondaMate_Graph_Project/.github/workflows/Release.yml@main


  Cleanup:
    needs: Release
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: WebHook Call [Cleanup]
        env:
          FOR_WEBHOOKS_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          echo "::add-mask::$FOR_WEBHOOKS_SECRET"
          curl --verbose --fail --show-error --location --request POST "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" --header "Authorization: token $FOR_WEBHOOKS_SECRET" --header 'Content-Type: application/json' --header 'Accept: application/vnd.github.everest-preview+json' --data-raw "{ \"event_type\": \"delete_all_artifacts\", \"client_payload\": {\"parent_runid\": \"$GITHUB_RUN_ID\", \"parent_repo\": \"$GITHUB_REPOSITORY\"} }"

#  Cleanup:
#    needs: Release
#    if: always()
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Repository Dispatch [Cleanup]
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.REPO_ACCESS_TOKEN }}
#          event-type: Cleanup-Artifacts
#          client-payload: '{"event_type": "delete_all_artifacts", "client_payload": {"parent_runid": "${{github.run_id}}", "parent_repo": "${{ github.repository }}"}}'
