name: Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  Release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - uses: actions/download-artifact@v3
        name: Download JAR artifact
        env:
          name: JAR_Releases

      - uses: softprops/action-gh-release@v1
        name: Release new release
        with:
          tag_name: ${{ github.ref_name }}
          files: ./JAR_Releases/*
