name: Tests

on:
  push:
    branches: [ main ]
    tags:
      - v**

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        name: Setup Java
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Tests
        run: mvn test


  Build:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: Test

    steps:
#testing reusable workflow
      - name: Repository Dispatch [Build]
        uses: peter-evans/repository-dispatch@v1
        with:
          parent_access_token: ${{ secrets.token }}
          event-type: Build
          client-payload: '{"ref": "${{ github.ref }}", "ref_name": "${{ github.ref_name }}"}'
#testing reusable workflow


#      - name: Repository Dispatch [Build]
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.REPO_ACCESS_TOKEN }}
#          secrets:
#            parent_access_token: ${{ secrets.token }}
#          event-type: Build
#          client-payload: '{"ref": "${{ github.ref }}", "ref_name": "${{ github.ref_name }}"}'
