name: Test

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Maven and dependancies
        run: |
          apt-get install default-jdk, default-jre, maven

      - name: Maven Tests
        run: |
          mvn test
