name: Tests

on:
  push:
    branches: [ main ]
    tags:
      - v**

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        name: Setup Java
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Tests
        run: mvn test


  Build:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: Test
    uses: GingerNinja2962/FoondaMate_Graph_Project/.github/workflows/Build.yml@main
#    with:
#      event-type: Build
#      client-payload: '{"ref": "${{ github.ref }}", "ref_name": "${{ github.ref_name }}"}'
    secrets:
      parent_access_token: ${{ secrets.token }}

#    steps:
#      - name: Repository Dispatch [Build]
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.REPO_ACCESS_TOKEN }}
#          secrets:
#            parent_access_token: ${{ secrets.token }}
#          event-type: Build
#          client-payload: '{"ref": "${{ github.ref }}", "ref_name": "${{ github.ref_name }}"}'

  Release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: Build
    uses: GingerNinja2962/FoondaMate_Graph_Project/.github/workflows/Release.yml@main
    #    with:
    #      event-type: Build
    #      client-payload: '{"ref": "${{ github.ref }}", "ref_name": "${{ github.ref_name }}"}'
    secrets:
      parent_access_token: ${{ secrets.token }}


  Cleanup:
    needs: Release
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch [Cleanup]
        if: always()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ github.token }}
          event-type: Cleanup-Artifacts
          client-payload: '{"event_type": "delete_all_artifacts", "client_payload": {"parent_runid": "${{github.run_id}}", "parent_repo": "${{ github.repository }}"}}'
