name: Run Tests

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker run
        run: docker-compose up -d
